### ISSUE TITLE
CUDA failure: ggml_new_object: not enough space in the context's memory pool

### ISSUE THREAD

**Issue by ruped** [phronmophobic/llama.clj#3]
It seems that `llama.clj` fails for large contexts (and large prompt) when using `llama.cpp` that is compiled with CUDA. It looks like the CUDA version may need more memory set somewhere?

Would really appreciate any help you can offer!

This may be a `llama.cpp` issues instead of a `llama.clj` issue: https://github.com/ggerganov/llama.cpp/issues/2404

### Code:

```
  (def prompt "Knees are the joints that connect the thigh bone (femur) to the shin bone (tibia) in the human body. They are essential for bending and straightening the leg, allowing for movement and mobility. The knee joint is made up of several components, including the patella (kneecap), the femoral and tibial condyles, and the ligaments that connect the bones and hold the joint together. The knee is a complex and highly specialized joint that plays a vital role in our ability to walk, run, and engage in other physical activities.

Knees are the joints that connect the thigh bone (femur) to the shin bone (tibia) in the human body. They are essential for bending and straightening the leg, allowing for movement and mobility. The knee joint is made up of several components, including the patella (kneecap), the femoral and tibial condyles, and the ligaments that connect the bones and hold the joint together. The knee is a complex and highly specialized joint that plays a vital role in our ability to walk, run, and engage in other physical activities.

Knees are the joints that connect the thigh bone (femur) to the shin bone (tibia) in the human body. They are essential for bending and straightening the leg, allowing for movement and mobility. The knee joint is made up of several components, including the patella (kneecap), the femoral and tibial condyles, and the ligaments that connect the bones and hold the joint together. The knee is a complex and highly specialized joint that plays a vital role in our ability to walk, run, and engage in other physical activities.

Knees are the joints that connect the thigh bone (femur) to the shin bone (tibia) in the human body. They are essential for bending and straightening the leg, allowing for movement and mobility. The knee joint is made up of several components, including the patella (kneecap), the femoral and tibial condyles, and the ligaments that connect the bones and hold the joint together. The knee is a complex and highly specialized joint that plays a vital role in our ability to walk, run, and engage in other physical activities.

Knees are the joints that connect the thigh bone (femur) to the shin bone (tibia) in the human body. They are essential for bending and straightening the leg, allowing for movement and mobility. The knee joint is made up of several components, including the patella (kneecap), the femoral and tibial condyles, and the ligaments that connect the bones and hold the joint together. The knee is a complex and highly specialized joint that plays a vital role in our ability to walk, run, and engage in other physical activities.

Translate the above into french.")

  (def model-path ",,,/llama-2-7b-chat.ggmlv3.q4_0.bin")
  (def ctx (create-context model-path {:n-ctx 4096}))
  (def x (time (doall (take 20 (generate ctx prompt)))))
```

### Note:
* No layers are actually being offloaded to GPU in either case.
* `llama.cpp` command line **works fine** with CUDA and large context sizes
* `llama.cpp` compiled with CUDA in llama.clj **works fine** for small prompts.

### Works:
`llama.clj` using `non-CUDA llama.cpp` works

 ie using the  `[com.phronemophobic.cljonda/llama-cpp-linux-x86-64 "6e88a462d7d2d281e33f35c3c41df785ef633bc1"]`

### Fails
`llama.clj` using `llama.cpp` compiled with cuda fails and JVM exits

`"-Djna.library.path=.../llama.cpp/build/"`

```
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1660 SUPER, compute capability 7.5
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 4141.73 MB (+ 2048.00 MB per state)
llama_model_load_internal: offloading 0 repeating layers to GPU
llama_model_load_internal: offloaded 0/35 layers to GPU
llama_model_load_internal: total VRAM used: 512 MB
llama_new_context_with_model: kv self size  = 2048.00 MB
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcda419a4c1, pid=109662, tid=109722
#
# JRE version: OpenJDK Runtime Environment (11.0.15+10) (build 11.0.15+10-Ubuntu-0ubuntu0.21.10.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.15+10-Ubuntu-0ubuntu0.21.10.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libllama.so+0x4c4c1]  ggml_new_tensor+0x291
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/luke/Webspaces/ruped-llama-clj/core.109662)
#
# An error report file with more information is saved as:
# /home/luke/Webspaces/ruped-llama-clj/hs_err_pid109662.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
ggml_new_object: not enough space in the context's memory pool (needed 11210656, available 10650320)
Subprocess failed
```

**Comment by phronmophobic** [comment]
I'm also able to reproduce on my m1 macbook air. The linked issue has some tips that I can look into.

> I cannot reproduce this with main, so I can only guess that it is something related to the python bindings that you are using.

and

>You could look into what parameters are being passed to llama_eval, this could be caused by a batch size larger than n_batch (n_tokens), or a value of n_past higher than n_ctx. We should probably add some checks.

It seems like since it works with llama.cpp, then it's probably something that should be fixed in llama.clj. There's an assert for checking that `n_past` is smaller than `n_ctx`, but there isn't a check for making sure that batches aren't larger than n_batch (n_tokens).

When I get a chance, I'll probably start there, but looking at the `hs_err_pid*` files can also be helpful.

**Comment by phronmophobic** [comment]
Increasing the batch size with `:n-batch` doesn't seem to help. For some reason, the `hs_err_pid` file isnt' being generated. If you're able to share yours, that could help, but it's probably possible to find a solution regardless.

**Comment by phronmophobic** [comment]
Ok, it seems like the main issue is probably that `llama-update` doesn't respect the batch size. I've created a branch for adding batching https://github.com/phronmophobic/llama.clj/tree/add-batching which seems to fix the issue.

There's still some work to do though:

- testing to make sure it's batching correctly
- batch size is currently hard coded to 512
- The llama.cpp API doesn't have way to access the batch size of a given context. We'll either need to 1) submit a pull request to llama.cpp to expose the batch size or 2) connect the params to a context so that they can be retrieved later. The second option is probably preferable.
- This would still hard crash if someone sets a larger batch size than their hardware can handle, but that's probably ok. Not sure there's actually a way to add a check to make sure the batch size isn't too big.

**Comment by phronmophobic** [comment]
It’s also unclear whether the batch size actually has anything to do with the context or model at all and should be a parameter to llama-update rather than a parameter to context creation.

**Comment by phronmophobic** [comment]
> It’s also unclear whether the batch size actually has anything to do with the context or model at all and should be a parameter to llama-update rather than a parameter to context creation.

It seems like n_batch is used to calculate how much memory to allocate.

**Comment by ruped** [comment]
Thanks so much for looking into this!

> > I cannot reproduce this with main, 

It's odd  (but true) that it is not reproduced on main - it's also not reproduced on server either [[link](https://github.com/ggerganov/llama.cpp/tree/master/examples/server)]. 

> For some reason, the hs_err_pid file isnt' being generated. If you're able to share yours, t

Will try and get this file tomorrow. I find these files get generated most consistently when running uberjars rather than inside a repl.

> This would still hard crash if someone sets a larger batch size than their hardware can handle, but that's probably ok

I think this is fine - most people tune their paramaters on the same hardware as production and can increase/decrease as needed.

> It seems like n_batch is used to calculate how much memory to allocate.

Here's the defintion of n_batch [[link](https://github.com/ggerganov/llama.cpp/tree/master/examples/main)]:
> Set the batch size for prompt processing (default: 512). This large batch size benefits users who have BLAS installed and enabled it during the build. If you don't have BLAS enabled ("BLAS=0"), you can use a smaller number, such as 8, to see the prompt progress as it's evaluated in some situations.

To me, this quote makes it sound rather uninteresting/irrelevant unless you care about seeing progress being loaded.

Not an urgent issue for me, but think it would be interesting to resolve for llama.clj in the long run.

**Comment by phronmophobic** [comment]
>To me, this quote makes it sound rather uninteresting/irrelevant unless you care about seeing progress being loaded.

I looked through the source and it seems like it does do allocations based on the size of `n_batch`:

https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L1301
https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L1301

**Comment by ruped** [comment]
Yes - I think this is an issue with their documentation - possibly leading to the n_batch not being used correctly everywhere in the code.

**Comment by phronmophobic** [comment]
I don't think there's anything wrong with their code. I think the problem is that llama.clj calls `llama_eval` with `num_tokens` larger than the batch size. I think the fix is to add batching inside of `llama_update`. See the https://github.com/phronmophobic/llama.clj/tree/add-batching branch for the WIP fix.

**Comment by ruped** [comment]
Excellent. I'll try out that  branch then. Thanks!

I assume this will still allow us to make use of the full 4,096 tokens of context from the Llama 2 model, even though it is batching 512 tokens?

**Comment by phronmophobic** [comment]
It should! Let me know if it doesn't or the output doesn't look right.

**Comment by ruped** [comment]
Will do, thanks.

**Comment by phronmophobic** [comment]
Ok, just merged the changes, https://github.com/phronmophobic/llama.clj/pull/4, into the main branch. Let me know if you see any issues.

I'll upload a new release to clojars soon.

**Comment by phronmophobic** [comment]
Afaict, this is now fixed. Feel free to reopen if I've missed something.
